<script lang="ts">
import { defineComponent, computed } from 'vue'
import type { PostMetadata, PostContent } from '@/utils/posts'

export const metadata: PostMetadata = {
  slug: 'skills-not-seats',
  date: '2026-09-19',
  tags: ['Software', 'AI', 'Opinion', 'Work']
}

const englishContent: PostContent = {
  title: 'The Skill Was Real. The Seat Wasn\'t.',
  description: 'Product ownership, testing, security, platform engineering: most of what got hired as a separate seat over the last ten years is a skill that never needed one. On my team the fix landed on the tech lead, who now carries product judgment next to the domain expertise he already had. One field report, not a template — and it updates something I only got half right two posts ago.',
  html: `<div class="post-tldr"><p><strong>TL;DR</strong> <abbr title="Product Owner — the Scrum role responsible for the backlog">PO</abbr>, <abbr title="Quality Assurance">QA</abbr>, security, <abbr title="Platform engineering and operations, often shortened to DevOps">DevOps</abbr>, and plenty of others: job titles that barely existed twenty years ago, now hired and promoted against as if they always had. Each names a real skill. None ever required a seat that could only do that one thing. On my team, the fix landed on the tech lead, who absorbed product ownership on top of domain expertise he already carried — one field report, not a template for every org. The general claim underneath it: heading into 2027, an <abbr title="Built around AI agents doing first-draft, first-pass work by default, not as an add-on">AI-native</abbr> team can no longer afford the coordination a seat was built to sell, and skills have to remerge into whoever already holds the accountability. This sharpens something I only got half right in an earlier post — I said it plainly there, I'll say it plainer here.</p></div>
<hr>
<p>Somewhere in the last decade, a set of skills got promoted into a payroll line.</p>
<p>Product Owner. QA engineer. Security engineer. DevOps engineer. And plenty of others. Job titles that did not exist as separate seats twenty years ago, and that most engineering organizations now hire, budget and promote against as if they always had. Each one names something real: product judgment, test judgment, security judgment, operational judgment. None of them ever required a person who could only do that one thing. Development and architecture went through a version of the same move at some organizations — a Solution Architect title peeled off the senior developer who used to just hold both — but that pairing mostly resisted the split. A tech lead, by default, is already the person who carries the development judgment and the architecture judgment; that was never the piece that needed its own seat. Somewhere between the first Scrum certification and the fortieth dedicated Slack channel, the other skills got seats instead, and the seats started acting like they needed protecting from the rest of the team.</p>
<p>This is a field report about what happens when you put the seat back where the skill came from. It worked on my team. I do not think the specific shape it took there — the tech lead absorbing product ownership and doubling down on domain expertise — is the shape it should take everywhere; a security-heavy fintech team would land somewhere else, and should. What I think generalizes, heading into 2027, is the diagnosis underneath it: the seat, not the skill, is what a fast organization can no longer afford, and if you are running on <abbr title="Built around AI agents doing first-draft, first-pass work by default, not as an add-on">AI-native</abbr> throughput, the org chart you inherited is now the slowest thing you own.</p>
<blockquote><p>A title bought coordination. It rarely bought the judgment it was named after.</p></blockquote>

<h2>What the decade actually built</h2>
<p>I want to be honest about the history before I argue with it, because the cynical version is also the lazy one. Three things happened at once, and only one of them deserves the accusation.</p>
<p>The first is real: complexity grew faster than any one engineer could hold. Security surface, cloud topology, regulatory traceability — each got deep enough that a generalist skimming all three was worse than a specialist owning one, at least at a given team size. The second is also real: once an organization outgrows a room everyone fits in, someone has to do cross-team integration, and that work is genuinely full-time past a certain scale. Frameworks built for that moment, like the Scaled Agile Framework, publish entire role catalogues — Product Owner, Release Train Engineer, Solution Architect — as the honest answer to a real coordination problem at hundreds of engineers.</p>
<p>The third is the one I am actually arguing with: those same catalogues got installed at teams a tenth that size, and the seat survived long after the coordination problem it solved had shrunk back down. Nobody wrote that down as a plan. It happened one restructuring at a time, each one locally reasonable — a promotion needed a title, a title needed a scope, a scope needed a headcount line to protect it. The result reads, from where I sit, less like specialization and more like a piloting layer: a seat whose main output was status, not judgment. Its existence let the people doing the work stop feeling responsible for the parts the seat now covered. That reading is mine. No framework I am about to cite makes it for me.</p>
<p><abbr title="Matthew Skelton and Manuel Pais, authors of the 2019 book on organizing teams around cognitive load">Team Topologies</abbr> gets closest to a citable version of the mechanism, and it argues something narrower than my claim: cognitive load is finite, so a team should shed every hand-off it does not need. <abbr title="DevOps Research and Assessment, Google Cloud's research program on software delivery">DORA</abbr>'s own research backs the same instinct from the systems side — elite performers are measurably more likely to run a loosely coupled architecture, precisely because it removes cross-team dependency on the critical path. Neither one argues for merging PO and security and domain expertise into a single person. What they argue is that every hand-off has a cost, and an organization that keeps adding seats without asking what hand-off each one adds is paying that cost blind.</p>
<p>The clearest real-world precedent for actually collapsing a seat, rather than just reducing its hand-offs, is the disappearance of a dedicated "operations" title. <abbr title="Amazon's chief technology officer">Werner Vogels</abbr> described it in 2006: giving Amazon's developers the operational responsibility for what they built raised quality on both sides of the old wall, because the two halves of the judgment — build it well, run it well — had never actually needed two different people. Netflix wrote the same move up a decade later as "full-cycle developers," folding the separate SRE and test-engineering seats back into the person writing the change. Testing and security are living through the same move right now, under the name "shift left": instead of a QA seat catching what a developer missed downstream, or a security seat gatekeeping a release at the end, the skill returns to whoever is already closest to the change when it is made.</p>

<svg viewBox="0 0 640 342" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Illustrative bar chart comparing four roles invented over the last decade — product ownership, testing, security, platform engineering — each split into a skill share that stays with the person and a seat share of coordination and reporting that does not; the seat share is the larger part in every row." class="diagram-svg">
<text x="32" y="32" fill="currentColor" font-family="ui-sans-serif, system-ui, sans-serif" font-size="14.5" font-weight="600" opacity="0.55" letter-spacing="0.14em">TEN YEARS OF NEW TITLES · ILLUSTRATIVE</text>
<text x="32" y="72" fill="currentColor" font-family="ui-sans-serif, system-ui, sans-serif" font-size="28" font-weight="650">The skill was real. The seat wasn't.</text>
<g fill="currentColor" font-family="ui-sans-serif, system-ui, sans-serif" font-size="13" font-weight="600" opacity="0.75">
<text x="32" y="100">Product ownership</text>
<text x="32" y="140">Testing</text>
<text x="32" y="180">Security</text>
<text x="32" y="220">Platform / DevOps</text>
</g>
<g stroke="currentColor" stroke-opacity="0.22" stroke-width="1">
<rect x="32" y="106" width="190" height="24" rx="8" fill="currentColor" fill-opacity="0.42"></rect>
<rect x="226" y="106" width="382" height="24" rx="8" fill="currentColor" fill-opacity="0.12"></rect>
<rect x="32" y="146" width="160" height="24" rx="8" fill="currentColor" fill-opacity="0.42"></rect>
<rect x="196" y="146" width="412" height="24" rx="8" fill="currentColor" fill-opacity="0.12"></rect>
<rect x="32" y="186" width="230" height="24" rx="8" fill="currentColor" fill-opacity="0.42"></rect>
<rect x="266" y="186" width="342" height="24" rx="8" fill="currentColor" fill-opacity="0.12"></rect>
<rect x="32" y="226" width="210" height="24" rx="8" fill="currentColor" fill-opacity="0.42"></rect>
<rect x="246" y="226" width="362" height="24" rx="8" fill="currentColor" fill-opacity="0.12"></rect>
</g>
<g font-family="ui-sans-serif, system-ui, sans-serif" font-size="13">
<rect x="32" y="266" width="14" height="14" rx="4" fill="currentColor" fill-opacity="0.42"></rect>
<text x="54" y="277" fill="currentColor" opacity="0.75">the skill — moves with the person</text>
<rect x="330" y="266" width="14" height="14" rx="4" fill="currentColor" fill-opacity="0.12" stroke="currentColor" stroke-opacity="0.22"></rect>
<text x="352" y="277" fill="currentColor" opacity="0.75">the seat — the title, the meetings, the reporting line</text>
</g>
<text x="32" y="312" fill="currentColor" font-family="ui-sans-serif, system-ui, sans-serif" font-size="13" font-style="italic" opacity="0.6">illustrative shares — a model of where the weight sits, not a measurement</text>
</svg>

<h2>One field report, not a template</h2>
<p>On <abbr title="Fictitious codename: the real project, its products and its vendor are anonymized.">Solstice*</abbr>, I am the tech lead for the engineering side of a hospital <abbr title="Enterprise Resource Planning — the administrative backbone of a hospital group">ERP</abbr>, and I have spent enough years in this domain that I could already argue a clinical workflow with a medical director before I ever touched a backlog. The tech lead title already meant I owned the architecture judgment and the development judgment — that was never in question, and it is not what changed. What changed is the third one: the business judgment, reading what a hospital actually needs and turning it into a priority, which used to sit with a separate PO. Over the past two quarters, I stopped handing product decisions to a separate PO and started making them myself, in the same conversation where I make the technical call. The weekly workshop that used to end with someone else writing tickets from my notes now ends with the tickets written, because the person deciding what we build and the person who understands why the certified module handles retention a certain way are the same person, in the same meeting, at the same time.</p>
<p>Naming why this was possible now, and not three years ago, matters more than the fact that it happened. The relay work that used to fill a PO's week — feeding the backlog, formatting tickets, chasing status for a steering committee — is exactly what I described agents absorbing in <a target="_blank" rel="noopener noreferrer" href="/posts/po-is-dead-judgment-is-not">an earlier post</a>. That absorption is not the argument of this post, but it is the precondition for it: it freed enough hours in a week for one person to hold product judgment and domain depth at the same time, without simply doubling that person's workload. Before agents did that packaging work, fusing the two roles meant either the product side or the technical side went shallow. Now it does not have to.</p>
<p>I want to be direct about what does not generalize from this. It worked because I already had ten years in this domain before I added the product skill on top — I was not asking a generalist to become an expert in two things at once, I was asking someone who already half-owned one of them to formally own both. "Promote your best engineer to also run the backlog" is a recipe for burnout if the second skill is not already half-built; it is a bus-factor problem if that person becomes the only one who can translate domain nuance into a technical constraint. Past roughly fifteen to twenty engineers, or more than one product surface, I would expect this exact shape to break — the fusion becomes two full-time jobs wearing one badge, not one job with better ergonomics. What generalizes is not "make your tech lead do this." It is: stop assuming a skill needs its own seat before checking whether it already lives next to the accountability you need.</p>

<h2>This sharpens something I only got half right</h2>
<p>I wrote, two posts ago, that <a target="_blank" rel="noopener noreferrer" href="/posts/po-is-dead-judgment-is-not">product judgment survives and diffuses across roles</a> — the engineer making micro-decisions hourly, the PM steering by delivery numbers, the PO feeding context through the workshop. That is still true at the scale that piece was describing: a multi-role team where the wall between product and engineering is dissolving from both sides at once. What I did not say clearly enough there is that diffusion has a shape, and the shape depends on how small the team gets. Spread thin enough — a squad small enough for one person to already hold the full context — diffusion does not stay spread. It collapses to one name. That is not a failure of the earlier argument. It is what the earlier argument looks like at the point where there is only one person left to diffuse to.</p>
<p>I am naming this directly because a reader of the series will notice the shift before I do it for them. The earlier post argued judgment should not consolidate into one role without a named answer to who signs and how juniors learn it. Both answers get harder, not easier, when the role is one person instead of four. I do not think that makes the fusion wrong. I think it makes the honest section below non-negotiable instead of optional.</p>
<blockquote><p>Judgment did not move to a title. It moved to whoever was already accountable and had room left in the week.</p></blockquote>

<svg viewBox="0 0 640 288" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Illustrative comparison of one product decision under two structures: routed through four separate seats it travels the full length of the bar before it is made; routed through one seat that already holds the skill and the accountability, most of that length disappears." class="diagram-svg">
<text x="32" y="32" fill="currentColor" font-family="ui-sans-serif, system-ui, sans-serif" font-size="14.5" font-weight="600" opacity="0.55" letter-spacing="0.14em">ONE DECISION, TWO STRUCTURES · ILLUSTRATIVE</text>
<text x="32" y="72" fill="currentColor" font-family="ui-sans-serif, system-ui, sans-serif" font-size="28" font-weight="650">One seat signs. The rest used to relay.</text>
<text x="32" y="100" fill="currentColor" font-family="ui-sans-serif, system-ui, sans-serif" font-size="13" font-weight="600" opacity="0.75">4 separate seats</text>
<rect x="32" y="106" width="540" height="28" rx="8" fill="currentColor" fill-opacity="0.16" stroke="currentColor" stroke-opacity="0.22" stroke-width="1"></rect>
<text x="32" y="160" fill="currentColor" font-family="ui-sans-serif, system-ui, sans-serif" font-size="13" font-weight="600" opacity="0.75">1 seat, skill attached</text>
<rect x="32" y="166" width="200" height="28" rx="8" fill="currentColor" fill-opacity="0.42" stroke="currentColor" stroke-opacity="0.22" stroke-width="1"></rect>
<path d="M 572 134 L 572 210 L 232 210 L 232 196" fill="none" stroke="currentColor" stroke-opacity="0.5" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
<path d="M 396 210 L 396 222" fill="none" stroke="currentColor" stroke-opacity="0.5" stroke-width="1.5" stroke-linecap="round"></path>
<text x="396" y="244" fill="currentColor" font-family="ui-sans-serif, system-ui, sans-serif" font-size="15" font-weight="650" text-anchor="middle">the hand-offs this removes</text>
<text x="32" y="272" fill="currentColor" font-family="ui-sans-serif, system-ui, sans-serif" font-size="13" font-style="italic" opacity="0.6">illustrative — the shape of what changes, not a measured latency</text>
</svg>

<h2>Where the seat still earns its keep</h2>
<p>None of this is an argument for fewer people. My team grew this year, interns and apprentices included, and the hours a merged title frees do not disappear into a smaller headcount line — they go to the discovery, domain depth and regulatory work that every post in this series has already argued was underfunded. Same logic as the DORA piece: the value is in reinvestment, not extraction.</p>
<p>And some of what a seat did is not overhead at all — it is a legal fact about how regulated software has to be built, and no amount of title redesign changes it. On Solstice*, the person who writes a safety-critical change cannot be the sole reviewer of its own verification; that is not a management preference, it is the segregation of duties an auditor checks for by name. Independent security review stays independent. A junior or apprentice still needs a name to shadow and a seat to grow into — collapsing a title does not collapse the need to teach the skill to someone who does not yet have it. And past the team size where one person can hold the full context, product-management-as-a-function stops being optional and becomes genuinely full-time again; I would not try this shape at ten times my team's size, and I would be wrong to recommend it there.</p>
<p>The honest list, stated plainly: independent verification on anything safety- or security-critical, a named accountable signer for every decision chain, and an on-ramp for whoever is supposed to inherit the skill next. None of those three survive being merged away. Everything else on the org chart is a candidate.</p>

<h2>What to do Monday morning</h2>
<ol>
<li><strong>Audit your titles, not your headcount.</strong> For each specialist seat, write two columns: the skill it protects, and the coordination it performs. If the second column is longer, you found a seat, not a skill.</li>
<li><strong>Pick one merge you already half-trust.</strong> Not the boldest one — the one where the person already owns half of the second skill informally.</li>
<li><strong>Name who still needs a wall, in writing.</strong> Independent security or safety review, immune to any merge, with a name attached, not a policy.</li>
<li><strong>Give the freed hours a destination before you announce the merge.</strong> Discovery, domain depth, teaching — not a shorter line on the org chart.</li>
<li><strong>Measure the thing you are claiming, not the vibe.</strong> Audit one real week: decision latency and meeting-hours, before the merge and after. Illustrative bars in a blog post are not evidence about your team.</li>
</ol>
<p><strong>Read the rest of the series:</strong> <a target="_blank" rel="noopener noreferrer" href="/posts/sdlc-is-dead">The SDLC Is Dead</a> — why the process was always waste. <a target="_blank" rel="noopener noreferrer" href="/posts/coder-is-dead-engineer-is-born">Coding Was Never the Job</a> — what the engineer becomes when syntax disappears. <a target="_blank" rel="noopener noreferrer" href="/posts/po-is-dead-judgment-is-not">The Backlog Was Never the Job</a> — the post this one sharpens: judgment diffuses across roles, until the team is small enough that it doesn't. <a target="_blank" rel="noopener noreferrer" href="/posts/doctrine-as-code">Doctrine Compounds. Models Don't.</a> — where the rules that outlive a merged role live. <a target="_blank" rel="noopener noreferrer" href="/posts/quality-is-executed">The Tests Passed. Nothing Happened.</a> — the other skill that stopped needing its own seat. <a target="_blank" rel="noopener noreferrer" href="/posts/dora-ai-roi-report">DORA Just Confirmed What My Team Already Lived</a> — the reinvestment logic this post reuses.</p>
<hr>
<h2>Sources</h2>
<ul>
<li><a target="_blank" rel="noopener noreferrer" href="https://teamtopologies.com/book">Team Topologies (Skelton & Pais, 2019)</a>: the cognitive-load argument for shedding unnecessary hand-offs at the team level. It argues for restructuring teams, not merging individual roles — I am extending its logic further than the authors do, and say so above.</li>
<li><a target="_blank" rel="noopener noreferrer" href="https://dora.dev/capabilities/loosely-coupled-teams/">DORA — Loosely coupled teams</a>: elite performers are measurably more likely to run architecture that removes cross-team dependency from the critical path. About systems, not job titles — the analogy is mine.</li>
<li><a target="_blank" rel="noopener noreferrer" href="https://queue.acm.org/detail.cfm?id=1142065">Jim Gray, A Conversation with Werner Vogels (ACM Queue, 2006)</a>: the origin of "you build it, you run it" — Amazon developers taking on operational responsibility for what they built.</li>
<li><a target="_blank" rel="noopener noreferrer" href="https://netflixtechblog.com/full-cycle-developers-at-netflix-a08c31f83249">Full Cycle Developers at Netflix (Netflix Tech Blog, 2018)</a>: Netflix folding separate SRE and test-engineering seats back into the developer, a decade after Vogels.</li>
<li>Solstice* — the workshop cycle and the team-size figures come from the team's own practice. Internal, no link: the codename is fictitious and the real project, its products and its vendor are anonymized.</li>
</ul>`
}

const frenchContent: PostContent = {
  title: 'La compétence était réelle. Le poste, non.',
  description: 'Product owner, test, sécurité, plateforme : la plupart de ce qui a été recruté comme poste séparé ces dix dernières années est une compétence qui n\'a jamais eu besoin d\'un poste. Chez moi, la solution est passée par le tech lead, qui porte désormais le jugement produit à côté de l\'expertise métier qu\'il avait déjà. Un retour d\'expérience, pas un modèle — et qui corrige quelque chose que je n\'avais qu\'à moitié dit il y a deux billets.',
  html: `<div class="post-tldr"><p><strong>TL;DR</strong> <abbr title="Product Owner — le rôle Scrum responsable du backlog">PO</abbr>, <abbr title="Quality Assurance — assurance qualité">QA</abbr>, sécurité, <abbr title="Ingénierie et exploitation de plateforme, souvent raccourci en DevOps">DevOps</abbr>, et bien d'autres : des intitulés de poste qui existaient à peine il y a vingt ans, aujourd'hui recrutés et promus comme s'ils avaient toujours existé. Chacun désigne une compétence réelle. Aucun n'a jamais exigé un poste incapable de faire autre chose. Chez moi, la solution est passée par le tech lead, qui a absorbé le product ownership par-dessus l'expertise métier qu'il portait déjà — un retour d'expérience, pas un modèle à copier partout. La thèse générale derrière : en route vers 2027, une équipe <abbr title="Construite pour que des agents IA produisent le premier jet par défaut, pas en option">IA-native</abbr> ne peut plus financer la coordination qu'un poste était censé vendre, et les compétences doivent se refondre vers qui porte déjà la responsabilité. Ça précise quelque chose que je n'avais qu'à moitié dit dans un billet précédent.</p></div>
<hr>
<p>Quelque part dans la dernière décennie, un ensemble de compétences a été promu en ligne de paie.</p>
<p>Product Owner. Ingénieur QA. Ingénieur sécurité. Ingénieur DevOps. Et bien d'autres. Des intitulés qui n'existaient pas comme postes séparés il y a vingt ans, et que la plupart des organisations d'ingénierie recrutent et budgètent aujourd'hui comme s'ils avaient toujours existé. Chacun désigne quelque chose de réel : le jugement produit, le jugement de test, le jugement sécurité, le jugement opérationnel. Aucun n'a jamais exigé une personne incapable de faire autre chose. Le développement et l'architecture ont connu une version du même mouvement dans certaines organisations — un intitulé « architecte solution » s'est détaché du développeur senior qui portait autrefois les deux — mais cette paire a surtout résisté à la scission. Un tech lead, par défaut, est déjà la personne qui porte le jugement de développement et le jugement d'architecture ; ça n'a jamais été la part qui avait besoin de son propre poste. Entre la première certification Scrum et le quarantième canal Slack dédié, les autres compétences ont reçu un poste à la place, et les postes se sont mis à agir comme si la compétence devait être protégée du reste de l'équipe.</p>
<p>Voici un retour d'expérience sur ce qui se passe quand on remet le poste là où la compétence est née. Ça a marché chez moi. Je ne pense pas que la forme précise que ça a prise — le tech lead absorbant le product ownership et approfondissant son expertise métier — soit la forme que ça doit prendre partout ; une équipe fintech très exposée à la sécurité atterrirait ailleurs — à juste titre. Ce qui se généralise, en route vers 2027, c'est le diagnostic derrière : c'est le poste, pas la compétence, qu'une organisation véloce ne peut plus financer, et si vous fonctionnez en régime <abbr title="Construite pour que des agents IA produisent le premier jet par défaut, pas en option">IA-native</abbr>, l'organigramme que vous avez hérité est désormais ce que vous avez de plus lent.</p>
<blockquote><p>Un poste achetait de la coordination. Il achetait rarement le jugement dont il portait le nom.</p></blockquote>

<h2>Ce que la décennie a vraiment construit</h2>
<p>Je veux être honnête sur l'histoire avant de la contester, parce que la version cynique est aussi la version paresseuse. Trois choses se sont produites en même temps, et une seule mérite l'accusation.</p>
<p>La première est réelle : la complexité a grandi plus vite qu'un seul ingénieur ne pouvait la porter. La surface de sécurité, la topologie cloud, la traçabilité réglementaire — chacune est devenue assez profonde pour qu'un généraliste survolant les trois fasse pire qu'un spécialiste n'en tenant qu'une, du moins à une certaine taille d'équipe. La deuxième est réelle aussi : une fois qu'une organisation dépasse une pièce où tout le monde tient, quelqu'un doit faire l'intégration entre équipes, et ce travail est réellement à temps plein passé une certaine échelle. Des cadres conçus pour ce moment-là, comme le Scaled Agile Framework, publient des catalogues entiers de rôles — Product Owner, Release Train Engineer, Solution Architect — comme la réponse honnête à un vrai problème de coordination sur des centaines d'ingénieurs.</p>
<p>La troisième est celle que je conteste vraiment : ces mêmes catalogues ont été installés dans des équipes dix fois plus petites, et le poste a survécu bien après que le problème de coordination qu'il résolvait s'était réduit. Personne n'a écrit ça comme un plan. C'est arrivé une réorganisation à la fois, chacune localement raisonnable — une promotion avait besoin d'un titre, un titre avait besoin d'un périmètre, un périmètre avait besoin d'une ligne d'effectif pour le protéger. Le résultat ressemble, de là où je suis, moins à de la spécialisation qu'à une couche de pilotage : un poste dont la production principale était du statut, pas du jugement. Son existence permettait aux gens qui faisaient le travail de cesser de se sentir responsables des parties que le poste couvrait désormais. Cette lecture est la mienne. Aucun des cadres que je vais citer ne la fait à ma place.</p>
<p><abbr title="Matthew Skelton et Manuel Pais, auteurs du livre de 2019 sur l'organisation des équipes autour de la charge cognitive">Team Topologies</abbr> s'approche le plus d'une version citable du mécanisme, et défend une thèse plus étroite que la mienne : la charge cognitive est finie, donc une équipe devrait se débarrasser de tout relais dont elle n'a pas besoin. Les propres recherches de <abbr title="DevOps Research and Assessment, le programme de recherche de Google Cloud sur le delivery logiciel">DORA</abbr> confortent le même instinct côté systèmes : les organisations les plus performantes sont mesurablement plus susceptibles d'adopter une architecture faiblement couplée, précisément parce que cela retire la dépendance inter-équipes du chemin critique. Ni l'un ni l'autre ne plaide pour fusionner le PO, la sécurité et l'expertise métier en une seule personne. Ce qu'ils défendent, c'est que chaque relais a un coût, et qu'une organisation qui continue d'ajouter des postes sans se demander quel relais chacun ajoute paie ce coût à l'aveugle.</p>
<p>Le précédent le plus net pour la disparition réelle d'un poste, plutôt que la simple réduction de ses relais, c'est la disparition d'un intitulé « opérations » dédié. <abbr title="Directeur technique d'Amazon">Werner Vogels</abbr> l'a décrit en 2006 : donner aux développeurs d'Amazon la responsabilité opérationnelle de ce qu'ils construisaient a fait monter la qualité des deux côtés de l'ancien mur, parce que les deux moitiés du jugement — bien construire, bien exploiter — n'avaient en réalité jamais eu besoin de deux personnes différentes. Netflix a écrit le même mouvement une décennie plus tard sous le nom de « full-cycle developers », en repliant les postes séparés de SRE et de test dans la personne qui écrit le changement. Le test et la sécurité vivent le même mouvement en ce moment, sous le nom de « shift left » : au lieu d'un poste QA qui attrape en aval ce qu'un développeur a manqué, ou d'un poste sécurité qui verrouille une livraison à la fin, la compétence revient à qui est déjà le plus proche du changement au moment où il est fait.</p>

<svg viewBox="0 0 640 342" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Diagramme illustratif comparant quatre rôles inventés ces dix dernières années — product ownership, test, sécurité, ingénierie de plateforme — chacun décomposé entre une part compétence qui reste avec la personne et une part poste, coordination et reporting, qui ne la suit pas ; la part poste est la plus grande dans chaque ligne." class="diagram-svg">
<text x="32" y="32" fill="currentColor" font-family="ui-sans-serif, system-ui, sans-serif" font-size="14.5" font-weight="600" opacity="0.55" letter-spacing="0.14em">DIX ANS DE NOUVEAUX POSTES · ILLUSTRATIF</text>
<text x="32" y="72" fill="currentColor" font-family="ui-sans-serif, system-ui, sans-serif" font-size="28" font-weight="650">La compétence était réelle. Le poste, non.</text>
<g fill="currentColor" font-family="ui-sans-serif, system-ui, sans-serif" font-size="13" font-weight="600" opacity="0.75">
<text x="32" y="100">Product ownership</text>
<text x="32" y="140">Test</text>
<text x="32" y="180">Sécurité</text>
<text x="32" y="220">Plateforme / DevOps</text>
</g>
<g stroke="currentColor" stroke-opacity="0.22" stroke-width="1">
<rect x="32" y="106" width="190" height="24" rx="8" fill="currentColor" fill-opacity="0.42"></rect>
<rect x="226" y="106" width="382" height="24" rx="8" fill="currentColor" fill-opacity="0.12"></rect>
<rect x="32" y="146" width="160" height="24" rx="8" fill="currentColor" fill-opacity="0.42"></rect>
<rect x="196" y="146" width="412" height="24" rx="8" fill="currentColor" fill-opacity="0.12"></rect>
<rect x="32" y="186" width="230" height="24" rx="8" fill="currentColor" fill-opacity="0.42"></rect>
<rect x="266" y="186" width="342" height="24" rx="8" fill="currentColor" fill-opacity="0.12"></rect>
<rect x="32" y="226" width="210" height="24" rx="8" fill="currentColor" fill-opacity="0.42"></rect>
<rect x="246" y="226" width="362" height="24" rx="8" fill="currentColor" fill-opacity="0.12"></rect>
</g>
<g font-family="ui-sans-serif, system-ui, sans-serif" font-size="13">
<rect x="32" y="266" width="14" height="14" rx="4" fill="currentColor" fill-opacity="0.42"></rect>
<text x="54" y="277" fill="currentColor" opacity="0.75">la compétence — suit la personne</text>
<rect x="330" y="266" width="14" height="14" rx="4" fill="currentColor" fill-opacity="0.12" stroke="currentColor" stroke-opacity="0.22"></rect>
<text x="352" y="277" fill="currentColor" opacity="0.75">le poste — le titre, les réunions, la ligne hiérarchique</text>
</g>
<text x="32" y="312" fill="currentColor" font-family="ui-sans-serif, system-ui, sans-serif" font-size="13" font-style="italic" opacity="0.6">parts illustratives — un modèle de la répartition du poids, pas une mesure</text>
</svg>

<h2>Un retour d'expérience, pas un modèle</h2>
<p>Sur <abbr title="Nom de code fictif : le projet réel, ses produits et son éditeur sont anonymisés.">Solstice*</abbr>, je suis tech lead côté ingénierie d'un <abbr title="Enterprise Resource Planning — la colonne vertébrale administrative d'un groupement hospitalier">ERP</abbr> hospitalier, et j'ai passé assez d'années dans ce domaine pour avoir déjà pu argumenter un parcours de soins face à un médecin-chef avant même de toucher un backlog. Le titre de tech lead impliquait déjà que je possédais le jugement d'architecture et le jugement de développement — ça n'a jamais été en question, et ce n'est pas ce qui a changé. Ce qui a changé, c'est le troisième : le jugement métier, comprendre ce dont un hôpital a réellement besoin et le transformer en priorité, qui reposait autrefois sur un PO séparé. Ces deux derniers trimestres, j'ai arrêté de confier les décisions produit à un PO séparé et j'ai commencé à les prendre moi-même, dans la même conversation où je prends la décision technique. L'atelier hebdomadaire qui se terminait autrefois par quelqu'un d'autre rédigeant des tickets à partir de mes notes se termine désormais avec les tickets déjà écrits, parce que la personne qui décide ce qu'on construit et la personne qui comprend pourquoi le module certifié gère la rétention d'une certaine façon sont la même personne, dans la même réunion, au même moment.</p>
<p>Dire pourquoi c'était possible maintenant, et pas il y a trois ans, compte plus que le fait que ça se soit produit. Le travail de relais qui remplissait autrefois la semaine d'un PO — alimenter le backlog, formater des tickets, courir après les statuts pour un comité de pilotage — c'est exactement le travail que les agents ont commencé à absorber, comme je l'ai décrit dans <a target="_blank" rel="noopener noreferrer" href="/posts/po-is-dead-judgment-is-not">un billet précédent</a>. Cette absorption n'est pas l'argument de ce billet-ci, mais elle en est la condition : elle a libéré assez d'heures dans une semaine pour qu'une seule personne porte le jugement produit et la profondeur métier en même temps, sans simplement doubler sa charge de travail. Avant que les agents ne fassent ce travail d'emballage, fusionner les deux rôles signifiait que le côté produit ou le côté technique devenait superficiel. Maintenant, ce n'est plus obligatoire.</p>
<p>Je veux être direct sur ce qui, dans mon cas, ne se généralise pas. Ça a marché parce que j'avais déjà dix ans dans ce domaine avant d'ajouter la compétence produit par-dessus — je ne demandais pas à un généraliste de devenir expert sur deux sujets à la fois, je demandais à quelqu'un qui maîtrisait déjà à moitié l'une des deux compétences d'assumer formellement les deux. « Promouvoir votre meilleur ingénieur pour qu'il gère aussi le backlog » est une recette d'épuisement si la seconde compétence n'est pas déjà à moitié construite ; c'est un problème de bus factor si cette personne devient la seule capable de traduire une nuance métier en contrainte technique. Passé environ quinze à vingt ingénieurs, ou plus d'un périmètre produit, je m'attendrais à ce que cette forme précise se casse — la fusion devient deux métiers à temps plein sous un seul badge, pas un métier avec une meilleure ergonomie. Ce qui se généralise, ce n'est pas « faites faire ça à votre tech lead ». C'est : arrêtez de supposer qu'une compétence a besoin de son propre poste avant d'avoir vérifié si elle vit déjà à côté de la responsabilité qu'il vous faut.</p>

<h2>Ça précise quelque chose que je n'avais qu'à moitié dit</h2>
<p>J'ai écrit, il y a deux billets, que <a target="_blank" rel="noopener noreferrer" href="/posts/po-is-dead-judgment-is-not">le jugement produit survit et se diffuse à travers les rôles</a> — l'ingénieur qui prend des micro-décisions à l'heure, le PM qui pilote sur des métriques de livraison, le PO qui nourrit le contexte par l'atelier. C'est toujours vrai à l'échelle que ce billet décrivait : une équipe multi-rôles où le mur entre produit et ingénierie se dissout des deux côtés à la fois. Ce que je n'ai pas assez clairement dit à l'époque, c'est que la diffusion a une forme, et que cette forme dépend de la taille de l'équipe. Sur une équipe assez petite pour qu'une seule personne porte déjà tout le contexte, la diffusion ne reste pas répartie. Elle s'effondre sur un seul nom. Ce n'est pas un échec de l'argument précédent. C'est ce à quoi il ressemble au point où il ne reste qu'une seule personne à qui diffuser.</p>
<p>Je le dis directement parce qu'un lecteur de la série remarquera le glissement avant que je ne le lui signale. Le billet précédent défendait que le jugement ne devrait pas se concentrer sur un seul rôle sans une réponse qui nomme qui signe et comment les juniors l'apprennent. Les deux réponses deviennent plus difficiles, pas plus faciles, quand le rôle est une personne au lieu de quatre. Je ne pense pas que cela rende la fusion fausse. Je pense que cela rend la section honnête ci-dessous non négociable plutôt que facultative.</p>
<blockquote><p>Le jugement n'a pas migré vers un titre. Il est allé vers qui portait déjà la responsabilité et avait encore de la place dans sa semaine.</p></blockquote>

<svg viewBox="0 0 640 288" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Comparaison illustrative d'une décision produit sous deux structures : relayée par quatre postes séparés, elle parcourt toute la longueur de la barre avant d'être prise ; relayée par un seul poste qui porte déjà la compétence et la responsabilité, l'essentiel de cette longueur disparaît." class="diagram-svg">
<text x="32" y="32" fill="currentColor" font-family="ui-sans-serif, system-ui, sans-serif" font-size="14.5" font-weight="600" opacity="0.55" letter-spacing="0.14em">UNE DÉCISION, DEUX STRUCTURES · ILLUSTRATIF</text>
<text x="32" y="72" fill="currentColor" font-family="ui-sans-serif, system-ui, sans-serif" font-size="28" font-weight="650">Un poste signe. Les autres relayaient.</text>
<text x="32" y="100" fill="currentColor" font-family="ui-sans-serif, system-ui, sans-serif" font-size="13" font-weight="600" opacity="0.75">4 postes séparés</text>
<rect x="32" y="106" width="540" height="28" rx="8" fill="currentColor" fill-opacity="0.16" stroke="currentColor" stroke-opacity="0.22" stroke-width="1"></rect>
<text x="32" y="160" fill="currentColor" font-family="ui-sans-serif, system-ui, sans-serif" font-size="13" font-weight="600" opacity="0.75">1 poste, compétence intégrée</text>
<rect x="32" y="166" width="200" height="28" rx="8" fill="currentColor" fill-opacity="0.42" stroke="currentColor" stroke-opacity="0.22" stroke-width="1"></rect>
<path d="M 572 134 L 572 210 L 232 210 L 232 196" fill="none" stroke="currentColor" stroke-opacity="0.5" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
<path d="M 396 210 L 396 222" fill="none" stroke="currentColor" stroke-opacity="0.5" stroke-width="1.5" stroke-linecap="round"></path>
<text x="396" y="244" fill="currentColor" font-family="ui-sans-serif, system-ui, sans-serif" font-size="15" font-weight="650" text-anchor="middle">les relais que ça supprime</text>
<text x="32" y="272" fill="currentColor" font-family="ui-sans-serif, system-ui, sans-serif" font-size="13" font-style="italic" opacity="0.6">illustratif — la forme de ce qui change, pas une latence mesurée</text>
</svg>

<h2>Là où le poste garde sa raison d'être</h2>
<p>Rien de tout cela n'est un argument pour moins de monde. Mon équipe a grandi cette année, alternants et apprentis inclus, et les heures qu'un poste fusionné libère ne disparaissent pas dans une ligne d'effectif plus courte — elles vont vers le terrain, la profondeur métier et le travail réglementaire que chaque billet de cette série a déjà qualifié de sous-financé. Même logique que le billet DORA : la valeur est dans le réinvestissement, pas dans l'extraction.</p>
<p>Et une partie de ce que faisait un poste n'a rien d'un coût : c'est un fait légal sur la façon dont le logiciel régulé doit être construit, et aucune refonte de titre ne le change. Sur Solstice*, la personne qui écrit un changement critique pour la sécurité des patients ne peut pas être la seule à relire sa propre vérification ; ce n'est pas une préférence de management, c'est la séparation des tâches qu'un auditeur vérifie nommément. La revue de sécurité indépendante reste indépendante. Un alternant ou un apprenti a toujours besoin de quelqu'un à observer et d'un poste vers lequel grandir — fusionner un titre ne fusionne pas le besoin d'enseigner la compétence à quelqu'un qui ne l'a pas encore. Et passé la taille d'équipe où une seule personne peut porter tout le contexte, le management produit en tant que fonction cesse d'être optionnel et redevient réellement un temps plein ; je n'essaierais pas cette forme à dix fois la taille de mon équipe, et j'aurais tort de la recommander à cette échelle.</p>
<p>La liste honnête, dite sans détour : la vérification indépendante sur tout ce qui touche à la sécurité des patients ou à la sûreté, un signataire responsable nommé pour chaque chaîne de décision, et une voie d'apprentissage pour qui doit hériter de la compétence ensuite. Aucun de ces trois ne survit à une fusion. Tout le reste de l'organigramme est candidat.</p>

<h2>Quoi faire lundi matin</h2>
<ol>
<li><strong>Auditez vos postes, pas vos effectifs.</strong> Pour chaque poste spécialisé, écrivez deux colonnes : la compétence qu'il protège, et la coordination qu'il effectue. Si la seconde colonne est plus longue, vous avez trouvé un poste, pas une compétence.</li>
<li><strong>Choisissez une fusion à laquelle vous croyez déjà à moitié.</strong> Pas la plus audacieuse — celle où la personne possède déjà informellement la moitié de la seconde compétence.</li>
<li><strong>Nommez par écrit qui a encore besoin d'un mur.</strong> Revue de sécurité ou de sûreté indépendante, immunisée contre toute fusion, avec un nom attaché, pas une politique.</li>
<li><strong>Donnez une destination aux heures libérées avant d'annoncer la fusion.</strong> Terrain, profondeur métier, enseignement — pas une ligne plus courte sur l'organigramme.</li>
<li><strong>Mesurez ce que vous affirmez, pas le ressenti.</strong> Auditez une vraie semaine : latence de décision et heures de réunion, avant la fusion et après. Des barres illustratives dans un billet de blog ne sont pas une preuve sur votre équipe.</li>
</ol>
<p><strong>Lire la suite de la série :</strong> <a target="_blank" rel="noopener noreferrer" href="/posts/sdlc-is-dead">Le SDLC est mort</a> — pourquoi le processus a toujours été du gaspillage. <a target="_blank" rel="noopener noreferrer" href="/posts/coder-is-dead-engineer-is-born">Coder n'a jamais été le métier</a> — ce que devient l'ingénieur quand la syntaxe disparaît. <a target="_blank" rel="noopener noreferrer" href="/posts/po-is-dead-judgment-is-not">Le backlog n'a jamais été le métier</a> — le billet que celui-ci précise : le jugement se diffuse à travers les rôles, jusqu'à ce que l'équipe soit trop petite pour ça. <a target="_blank" rel="noopener noreferrer" href="/posts/doctrine-as-code">La doctrine capitalise. Pas les modèles.</a> — où vivent les règles qui survivent à un rôle fusionné. <a target="_blank" rel="noopener noreferrer" href="/posts/quality-is-executed">Les tests passent. Il ne se passe rien.</a> — l'autre compétence qui a cessé d'avoir besoin de son propre poste. <a target="_blank" rel="noopener noreferrer" href="/posts/dora-ai-roi-report">DORA vient de confirmer ce que mon équipe a déjà vécu</a> — la logique de réinvestissement que ce billet réutilise.</p>
<hr>
<h2>Sources</h2>
<ul>
<li><a target="_blank" rel="noopener noreferrer" href="https://teamtopologies.com/book">Team Topologies (Skelton & Pais, 2019)</a> : l'argument de la charge cognitive pour se débarrasser des relais inutiles au niveau de l'équipe. Plaide pour restructurer des équipes, pas fusionner des rôles individuels — j'étends sa logique plus loin que les auteurs, et je le dis plus haut.</li>
<li><a target="_blank" rel="noopener noreferrer" href="https://dora.dev/capabilities/loosely-coupled-teams/">DORA — Loosely coupled teams</a> : les organisations les plus performantes sont mesurablement plus susceptibles de faire tourner une architecture qui retire la dépendance inter-équipes du chemin critique. Concerne les systèmes, pas les intitulés de poste — l'analogie est mienne.</li>
<li><a target="_blank" rel="noopener noreferrer" href="https://queue.acm.org/detail.cfm?id=1142065">Jim Gray, A Conversation with Werner Vogels (ACM Queue, 2006)</a> : l'origine de « you build it, you run it » — les développeurs d'Amazon prenant la responsabilité opérationnelle de ce qu'ils construisaient.</li>
<li><a target="_blank" rel="noopener noreferrer" href="https://netflixtechblog.com/full-cycle-developers-at-netflix-a08c31f83249">Full Cycle Developers at Netflix (Netflix Tech Blog, 2018)</a> : Netflix repliant les postes séparés de SRE et de test dans le développeur, une décennie après Vogels.</li>
<li>Solstice* — le cycle d'atelier et les chiffres de taille d'équipe viennent de la pratique de l'équipe elle-même. Interne, sans lien : le nom de code est fictif et le projet réel, ses produits et son éditeur sont anonymisés.</li>
</ul>`
}

export function getContent(locale: 'fr' | 'en'): PostContent {
  return locale === 'fr' ? frenchContent : englishContent
}

export default defineComponent({
  name: 'SkillsNotSeats',
  props: {
    locale: {
      type: String as () => 'fr' | 'en',
      required: true
    }
  },
  setup(props) {
    const content = computed(() => {
      return getContent(props.locale)
    })
    return { content }
  },
  template: '<div v-html="content.html"></div>'
})
</script>

<template>
  <div v-html="content.html"></div>
</template>
